package paquete;
// Generated 1 dic. 2021 15:55:45 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Affiliations generated by hbm2java
 */
public class Affiliations implements java.io.Serializable {

	private int id;
	private String affiliation;
	private Set<Characters> characterses = new HashSet<Characters>(0);

	public Affiliations() {
	}

	public Affiliations(int id) {
		this.id = id;
	}

	public Affiliations(int id, String affiliation, Set<Characters> characterses) {
		this.id = id;
		this.affiliation = affiliation;
		this.characterses = characterses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getAffiliation() {
		return this.affiliation;
	}

	public void setAffiliation(String affiliation) {
		this.affiliation = affiliation;
	}

	public Set<Characters> getCharacterses() {
		return this.characterses;
	}

	public void setCharacterses(Set<Characters> characterses) {
		this.characterses = characterses;
	}

}
