package paquete;
// Generated 1 dic. 2021 15:55:45 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Characters generated by hbm2java
 */
public class Characters implements java.io.Serializable {

	private int id;
	private Planets planets;
	private String name;
	private Integer height;
	private Float mass;
	private String hairColor;
	private String skinColor;
	private String eyeColor;
	private String birthYear;
	private String gender;
	private Date createdDate;
	private Date updatedDate;
	private String url;
	private Set<Affiliations> affiliationses = new HashSet<Affiliations>(0);
	private Set<Films> filmses = new HashSet<Films>(0);
	private Set<Deaths> deathsesForIdKiller = new HashSet<Deaths>(0);
	private Set<Deaths> deathsesForIdCharacter = new HashSet<Deaths>(0);

	public Characters() {
	}

	public Characters(int id, Planets planets, Date createdDate, Date updatedDate) {
		this.id = id;
		this.planets = planets;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public Characters(int id, Planets planets, String name, Integer height, Float mass, String hairColor,
			String skinColor, String eyeColor, String birthYear, String gender, Date createdDate, Date updatedDate,
			String url, Set<Affiliations> affiliationses, Set<Films> filmses, Set<Deaths> deathsesForIdKiller,
			Set<Deaths> deathsesForIdCharacter) {
		this.id = id;
		this.planets = planets;
		this.name = name;
		this.height = height;
		this.mass = mass;
		this.hairColor = hairColor;
		this.skinColor = skinColor;
		this.eyeColor = eyeColor;
		this.birthYear = birthYear;
		this.gender = gender;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.url = url;
		this.affiliationses = affiliationses;
		this.filmses = filmses;
		this.deathsesForIdKiller = deathsesForIdKiller;
		this.deathsesForIdCharacter = deathsesForIdCharacter;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Planets getPlanets() {
		return this.planets;
	}

	public void setPlanets(Planets planets) {
		this.planets = planets;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public Float getMass() {
		return this.mass;
	}

	public void setMass(Float mass) {
		this.mass = mass;
	}

	public String getHairColor() {
		return this.hairColor;
	}

	public void setHairColor(String hairColor) {
		this.hairColor = hairColor;
	}

	public String getSkinColor() {
		return this.skinColor;
	}

	public void setSkinColor(String skinColor) {
		this.skinColor = skinColor;
	}

	public String getEyeColor() {
		return this.eyeColor;
	}

	public void setEyeColor(String eyeColor) {
		this.eyeColor = eyeColor;
	}

	public String getBirthYear() {
		return this.birthYear;
	}

	public void setBirthYear(String birthYear) {
		this.birthYear = birthYear;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Set<Affiliations> getAffiliationses() {
		return this.affiliationses;
	}

	public void setAffiliationses(Set<Affiliations> affiliationses) {
		this.affiliationses = affiliationses;
	}

	public Set<Films> getFilmses() {
		return this.filmses;
	}

	public void setFilmses(Set<Films> filmses) {
		this.filmses = filmses;
	}

	public Set<Deaths> getDeathsesForIdKiller() {
		return this.deathsesForIdKiller;
	}

	public void setDeathsesForIdKiller(Set<Deaths> deathsesForIdKiller) {
		this.deathsesForIdKiller = deathsesForIdKiller;
	}

	public Set<Deaths> getDeathsesForIdCharacter() {
		return this.deathsesForIdCharacter;
	}

	public void setDeathsesForIdCharacter(Set<Deaths> deathsesForIdCharacter) {
		this.deathsesForIdCharacter = deathsesForIdCharacter;
	}

}
