package paquete;
// Generated 1 dic. 2021 15:55:45 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Films generated by hbm2java
 */
public class Films implements java.io.Serializable {

	private int id;
	private String episode;
	private String title;
	private Set<Characters> characterses = new HashSet<Characters>(0);
	private Set<Deaths> deathses = new HashSet<Deaths>(0);

	public Films() {
	}

	public Films(int id) {
		this.id = id;
	}

	public Films(int id, String episode, String title, Set<Characters> characterses, Set<Deaths> deathses) {
		this.id = id;
		this.episode = episode;
		this.title = title;
		this.characterses = characterses;
		this.deathses = deathses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getEpisode() {
		return this.episode;
	}

	public void setEpisode(String episode) {
		this.episode = episode;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Set<Characters> getCharacterses() {
		return this.characterses;
	}

	public void setCharacterses(Set<Characters> characterses) {
		this.characterses = characterses;
	}

	public Set<Deaths> getDeathses() {
		return this.deathses;
	}

	public void setDeathses(Set<Deaths> deathses) {
		this.deathses = deathses;
	}

}
