package paquete;
// Generated 1 dic. 2021 15:55:45 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Planets generated by hbm2java
 */
public class Planets implements java.io.Serializable {

	private int id;
	private String name;
	private Integer rotationPeriod;
	private Integer orbitalPeriod;
	private Integer diameter;
	private String climate;
	private String gravity;
	private String terrain;
	private String surfaceWater;
	private Long population;
	private Date createdDate;
	private Date updatedDate;
	private String url;
	private Set<Characters> characterses = new HashSet<Characters>(0);

	public Planets() {
	}

	public Planets(int id, Date createdDate, Date updatedDate) {
		this.id = id;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public Planets(int id, String name, Integer rotationPeriod, Integer orbitalPeriod, Integer diameter, String climate,
			String gravity, String terrain, String surfaceWater, Long population, Date createdDate, Date updatedDate,
			String url, Set<Characters> characterses) {
		this.id = id;
		this.name = name;
		this.rotationPeriod = rotationPeriod;
		this.orbitalPeriod = orbitalPeriod;
		this.diameter = diameter;
		this.climate = climate;
		this.gravity = gravity;
		this.terrain = terrain;
		this.surfaceWater = surfaceWater;
		this.population = population;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.url = url;
		this.characterses = characterses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getRotationPeriod() {
		return this.rotationPeriod;
	}

	public void setRotationPeriod(Integer rotationPeriod) {
		this.rotationPeriod = rotationPeriod;
	}

	public Integer getOrbitalPeriod() {
		return this.orbitalPeriod;
	}

	public void setOrbitalPeriod(Integer orbitalPeriod) {
		this.orbitalPeriod = orbitalPeriod;
	}

	public Integer getDiameter() {
		return this.diameter;
	}

	public void setDiameter(Integer diameter) {
		this.diameter = diameter;
	}

	public String getClimate() {
		return this.climate;
	}

	public void setClimate(String climate) {
		this.climate = climate;
	}

	public String getGravity() {
		return this.gravity;
	}

	public void setGravity(String gravity) {
		this.gravity = gravity;
	}

	public String getTerrain() {
		return this.terrain;
	}

	public void setTerrain(String terrain) {
		this.terrain = terrain;
	}

	public String getSurfaceWater() {
		return this.surfaceWater;
	}

	public void setSurfaceWater(String surfaceWater) {
		this.surfaceWater = surfaceWater;
	}

	public Long getPopulation() {
		return this.population;
	}

	public void setPopulation(Long population) {
		this.population = population;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Set<Characters> getCharacterses() {
		return this.characterses;
	}

	public void setCharacterses(Set<Characters> characterses) {
		this.characterses = characterses;
	}

}
