package paquete;
// Generated 17 dic. 2021 16:45:22 by Hibernate Tools 5.4.32.Final

/**
 * Books generated by hbm2java
 */
public class Books implements java.io.Serializable {

	private int id;
	private String title;
	private Integer year;
	private Integer subject;

	public Books() {
	}

	public Books(int id) {
		this.id = id;
	}

	public Books(int id, String title, Integer year, Integer subject) {
		this.id = id;
		this.title = title;
		this.year = year;
		this.subject = subject;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public Integer getSubject() {
		return this.subject;
	}

	public void setSubject(Integer subject) {
		this.subject = subject;
	}

}
